[package]
name = "wl-library-link-sys"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
edition = "2018"

# TODO: Use the 'links' key?
#       See: https://doc.rust-lang.org/cargo/reference/build-scripts.html#a-sys-packages

[dependencies]

[build-dependencies]
bindgen = "^0.31"
lazy_static = "^1.1"