[package]
name = "wl-library-link"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
edition = "2018"
publish = false

[dependencies]
wl-library-link-sys = { git = "ssh://github.com/ConnorGray/wl-library-link-sys.git" }
wl-expr = { git = "ssh://github.com/ConnorGray/wl-expr.git" }
wl-lang = { git = "ssh://github.com/ConnorGray/wl-lang.git" }
wl-parse = { git = "ssh://github.com/ConnorGray/wl-parse.git" }
