[package]
name = "wl-library-link-sys"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
edition = "2018"
publish = false

# TODO: Use the 'links' key?
#       See: https://doc.rust-lang.org/cargo/reference/build-scripts.html#a-sys-packages

[dependencies]

[build-dependencies]
# Use an exact, known-good version, since we really don't want small bugs in bindgen to a
# be a problem when running `cargo build` for the first time.
bindgen = "=0.32"
# lazy_static = "^1.1"