[package]
name = "wl-library-link"
version = "0.1.0"
authors = ["Connor Gray <accounts@connorgray.com>"]
edition = "2018"

[dependencies]
wl-library-link-sys = { path = "../wl-library-link-sys" }
wl-expr = { path = "../wl-expr" }
wl-lang = { path = "../wl-lang" }
wl-parser = { path = "../wl-parser" }
