[config]
default_to_workspace = false

#-----------------
# Task definitions
#-----------------

[tasks.paclet]
dependencies = ["copy-library-resources"]
script = { file = "./scripts/BuildPaclet.wls"}

[tasks.copy-library-resources]
dependencies = ["clean-library-resources", "build-library-resources"]
script = '''
mkdir RustLink/LibraryResources
cp ./target/debug/examples/libraw_wstp_function.dylib ./RustLink/LibraryResources/
'''

[tasks.clean-library-resources]
script = '''
rm -rf ./RustLink/LibraryResources
'''

[tasks.build-library-resources]
command = "cargo"
args = ["build", "--examples"]
