[config]
default_to_workspace = false

#=======================================
# Task definitions
#=======================================

#-----------
# Main tasks
#-----------

[tasks.paclet]
dependencies = ["clean-library-resources", "build-library-resources"]
script = { file = "./scripts/BuildPaclet.wls"}

[tasks.paclet-test]
dependencies = ["paclet"]
script = { file = "./scripts/RunTests.wls"}

#--------------------
# Building the paclet
#--------------------

[tasks.clean-library-resources]
script = '''
rm -rf ./RustLink/LibraryResources
'''

[tasks.build-library-resources]
command = "cargo"
args = ["build", "--examples"]
